tasks:
- init: ./gradlew compileTestJava compileJava

vscode:
  extensions:
    - vscjava.vscode-java-pack
    - redhat.java
    - vscjava.vscode-java-debug
    - vscjava.vscode-java-dependency
    - vscjava.vscode-java-test
    - richardwillis.vscode-gradle
    - vscjava.vscode-maven
    - EditorConfig.EditorConfig
