site_name: Defensive Works
site_description: Multi layered defense strategies for everyone
site_url: https://defensive.works
site_author: Raajhesh Kannaa Chidambaram

docs_dir: content

theme:
  name: material
  palette:
    - scheme: default 
  logo: images/logo.png
  favicon: images/logo.png
  custom_dir: overrides
  icon:
    repo: fontawesome/brands/github
  features:
    # - navigation.instant  Add this at a later date
    - navigation.tabs
    - navigation.indexes
  palette:
    - scheme: default
      primary: indigo
      toggle:
        icon: material/lightbulb
        name: Switch to Light Mode
    - scheme: slate
      primary: blue grey 
      toggle:
        icon: material/lightbulb-outline
        name: Switch to Dark Mode

markdown_extensions:
  - meta
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

plugins:
  - search
  - awesome-pages # non-standard
#  - minify:
#      minify_html: true
#      minify_js: true
#      minify_css: true

#extra_javascript:
#  - javascripts/matomo.min.js

#repo_name: Defensive Works 
#repo_url: https://github.com/raajheshkannaa/defensive.works
#edit_uri: edit/main/content/

extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/raajheshkannaa
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/raajhesh-kannaa-chidambaram/
    - icon: fontawesome/brands/github
      link: https://github.com/raajheshkannaa
